package com.mycompany.view;

import com.mycompany.clientleilao.ClientAuction;
import javax.swing.SwingUtilities;

/**
 *
 * @author nandones
 */
public class requestToJoinMulticastPanel extends javax.swing.JPanel {

    /**
     * Creates new form Panel1
     */
    public requestToJoinMulticastPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        labelTitle = new javax.swing.JLabel();
        buttonJoinMulticastRoom = new javax.swing.JButton();
        labelDescription = new javax.swing.JLabel();
        labelServerAdress = new javax.swing.JLabel();
        labelServerPort = new javax.swing.JLabel();
        textFieldServerAdress = new javax.swing.JTextField();
        textFieldServerPort = new javax.swing.JTextField();
        labelErrorDynamic = new javax.swing.JLabel();

        jButton1.setText("switch panel");

        labelTitle.setText("!JAVA AUCTIONS?");

        buttonJoinMulticastRoom.setText("join auction");
        buttonJoinMulticastRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonJoinMulticastRoomActionPerformed(evt);
            }
        });

        labelDescription.setText("Welcome! you want to join the auction room? fill the following fields.");

        labelServerAdress.setText("Server Adress:");

        labelServerPort.setText("Server Port:");

        textFieldServerAdress.setText("192.168.3.15");
        textFieldServerAdress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldServerAdressActionPerformed(evt);
            }
        });

        textFieldServerPort.setText("12345");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonJoinMulticastRoom))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(labelDescription))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(183, 183, 183)
                                .addComponent(labelTitle))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelServerAdress)
                                    .addComponent(labelServerPort))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textFieldServerPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldServerAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 76, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelErrorDynamic)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitle)
                .addGap(12, 12, 12)
                .addComponent(labelDescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelServerAdress)
                    .addComponent(textFieldServerAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelServerPort)
                    .addComponent(textFieldServerPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(labelErrorDynamic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(buttonJoinMulticastRoom)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonJoinMulticastRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonJoinMulticastRoomActionPerformed
        String serverAdress = textFieldServerAdress.getText();
        int serverPort = Integer.parseInt(textFieldServerPort.getText());
        boolean connection = ClientAuction.connectsToMulticast(serverAdress, serverPort);
        if (!connection) {
            labelErrorDynamic.setText("server not found!");
        } else {
            MainFrame mainFrame = (MainFrame) SwingUtilities.getWindowAncestor(this);
            mainFrame.switchPanel(new Panel2());
        }
    }//GEN-LAST:event_buttonJoinMulticastRoomActionPerformed

    private void textFieldServerAdressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldServerAdressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldServerAdressActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonJoinMulticastRoom;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel labelDescription;
    private javax.swing.JLabel labelErrorDynamic;
    private javax.swing.JLabel labelServerAdress;
    private javax.swing.JLabel labelServerPort;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JTextField textFieldServerAdress;
    private javax.swing.JTextField textFieldServerPort;
    // End of variables declaration//GEN-END:variables
}
